name: Pages deploy

on:
  push:
    branches: ["master"]

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/configure-pages@v2
    - uses: actions/setup-node@v2
    - uses: pnpm/action-setup@v2
    - name: Build
      run: |
        pnpm install
        pnpm run build
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v1
      with:
        path: dist
    - name: Deploy to Pages
      id: deployment
      uses: actions/deploy-pages@v1
